---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: demo-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - env:
        - name: HTTP_ADDR
          value: :8082
        - name: TELEMETRY_ADDR
          value: :8080
        image: nephe/demo-app:6425b08
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
        name: demo-app
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 80m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 80Mi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-app
spec:
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 40 
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
